### ISSUE TITLE
下载十分缓慢

### ISSUE THREAD

**Issue by Bo-He-J** [infstellar/python-git-program-launcher#17]
更新依赖的时候下载速度感人，只有10kb左右的速度

**Comment by ucasyfp** [comment]
好像是阿里源出了问题。把文件夹中main.py中的一行http://mirrors.aliyun.com/pypi/simple 改成 https://pypi.tuna.tsinghua.edu.cn/simple应该可以解决。

**Comment by Bo-He-J** [comment]
> 好像是阿里源出了问题。把文件夹中 main.py 中的一行 http://mirrors.aliyun.com/pypi/simple 改成 [https://pypi.tuna.tsinghua.edu.cn/simple 应该可以解决。](https://pypi.tuna.tsinghua.edu.cn/simple%E5%BA%94%E8%AF%A5%E5%8F%AF%E4%BB%A5%E8%A7%A3%E5%86%B3%E3%80%82)

确实，解决了

**Comment by infstellar** [comment]
实际上的解决方案应该是到GUI的配置页面把pip源地址给改了...
使用阿里源的原因是更新快，同步好像只要半天时间，清华源要更久。但是好像阿里源慢的感人，以后可能会换。
