### ISSUE TITLE
一个报错

### ISSUE THREAD

**Issue by woshiyouzidddd** [infstellar/python-git-program-launcher#20]
打开Launcher.exe时提示'python' 不是内部或外部命令，也不是可运行的程序

**Comment by infstellar** [comment]
发日志或者报错截图

**Comment by 2891337138** [comment]
![Uploading 屏幕截图 2024-05-16 224944.png…]()

**Comment by 2891337138** [comment]
![屏幕截图 2024-05-16 224944](https://github.com/infstellar/python-git-program-launcher/assets/139598837/f6f77c0e-43f5-470e-870c-f03fd4b1edb3)
![屏幕截图 2024-05-16 224944](https://github.com/infstellar/python-git-program-launcher/assets/139598837/81e80abb-d6db-4457-82a3-e66c4a2afe1a)

**Comment by infstellar** [comment]
> ![屏幕截图 2024-05-16 224944](https://private-user-images.githubusercontent.com/139598837/331257812-f6f77c0e-43f5-470e-870c-f03fd4b1edb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzIzMzAsIm5iZiI6MTcxNTg3MjAzMCwicGF0aCI6Ii8xMzk1OTg4MzcvMzMxMjU3ODEyLWY2Zjc3YzBlLTQzZjUtNDcwZS04NzBjLWYwM2ZkNGIxZWRiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNTA3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDUyZDg1ZDQ2Mjg4NTdmMjM3YTEyNWQxMDA2N2YyZjZmMmIzZDRmZjIzZDZjMjdkMjk0M2U3ZTRiYmE4NjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hr2gjW1Br38lyfZWtx-C2SgbFQCRbNJrUHMc9C_qBOo) ![屏幕截图 2024-05-16 224944](https://private-user-images.githubusercontent.com/139598837/331257882-81e80abb-d6db-4457-82a3-e66c4a2afe1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzIzMzAsIm5iZiI6MTcxNTg3MjAzMCwicGF0aCI6Ii8xMzk1OTg4MzcvMzMxMjU3ODgyLTgxZTgwYWJiLWQ2ZGItNDQ1Ny04MmEzLWU2NmM0YTJhZmUxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNTA3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDkyZDNlODBhMzYwMzNhYWVkYWFlN2ExZmJjNjRjOTVlNjZjNGYyZDU5NjA2OTQ0ODkzNGQxMjcwYzRiMDgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.952KqjOnSmvuQWv09muIwAzmy_IiRKaBME_OBl9Tk1g)

https://github.com/infstellar/python-git-program-launcher/releases/tag/v2.3.0
下载PGPL-2.3.7z

**Comment by 2891337138** [comment]
感谢大佬
