### ISSUE TITLE
由于找不到 libgcc_s_seh-1.dll，无法继续执行代码。重新安装程序可能会解决此问题。

### ISSUE THREAD

**Issue by C0deH0st** [infstellar/python-git-program-launcher#23]
---------------------------
Launcher.exe - 系统错误
---------------------------
由于找不到 libgcc_s_seh-1.dll，无法继续执行代码。重新安装程序可能会解决此问题。 
---------------------------
Launcher.exe - 系统错误
---------------------------
由于找不到 libstdc++-6.dll，无法继续执行代码。重新安装程序可能会解决此问题。

**Comment by infstellar** [comment]
fixed
