### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by qwqmaomao** [infstellar/python-git-program-launcher#29]
PATH=C:\WINDOWS\system32\toolkit;C:\WINDOWS\system32\toolkit\Scripts;C:\WINDOWS\system32\toolkit\Lib;C:\WINDOWS\system32\toolkit\Git\mingw64\bin;%PATH%
cd /d C:\WINDOWS\system32 && python -m gui
'python' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Fatal Error: Program Run Failure.
Running automatic error checking...
Possible reason: toolkit is not installed. Please check if you downloaded the correct file or if you cloned the submodule.
请按任意键继续. . .

**Comment by qwqmaomao** [comment]
> PATH=C:\WINDOWS\system32\toolkit;C:\WINDOWS\system32\toolkit\Scripts;C:\WINDOWS\system32\toolkit\Lib;C:\WINDOWS\system32\toolkit\Git\mingw64\bin;%PATH % cd /d C:\WINDOWS\system32 && python -m gui 'python' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 Fatal Error: Program Run Failure. 运行自动错误检查... 可能的原因：未安装工具包。请检查您是否下载了正确的文件或是否克隆了子模块。 请按任意键继续。。。

**Comment by qwqmaomao** [comment]
已解决，我的问题

**Comment by qwqmaomao** [comment]
> > 已解决，我的问题
> 
> 请问如何解决的



> > 已解决，我的问题
> 
> 请问如何解决的

如果使用下载压缩包的形式化，/
[pgpl 工具包](https://github.com/infstellar/pgpl-toolkit)需要额外下载，此报错正是缺乏此文件

**Comment by Yangswd** [comment]
> > > 已解决，我的问题
> > 
> > 
> > 请问如何解决的
> 
> > > 已解决，我的问题
> > 
> > 
> > 请问如何解决的
> 
> 如果使用下载压缩包的形式化，/ [pgpl 工具包](https://github.com/infstellar/pgpl-toolkit)需要额外下载，此报错正是缺乏此文件

请问是哪个工具包，为什么我下载后仍然问题没有解决

**Comment by infstellar** [comment]
> 请问是哪个工具包，为什么我下载后仍然问题没有解决

https://github.com/infstellar/python-git-program-launcher/releases/tag/v2.3.0
下载PGPL-2.3.7z
