### ISSUE TITLE
启动器失败报错No such file or directory

### ISSUE THREAD

**Issue by mengciyuanpoi** [infstellar/python-git-program-launcher#33]
![image](https://github.com/infstellar/python-git-program-launcher/assets/146476073/e63a4dc9-9229-4531-9912-bcff7c666cef)

**Comment by mengciyuanpoi** [comment]
[2023-09-30.log](https://github.com/infstellar/python-git-program-launcher/files/12774765/2023-09-30.log)

**Comment by infstellar** [comment]
fixed in v2.3
