### ISSUE TITLE
win11启动器打开后报错，找不到win32gui

### ISSUE THREAD

**Issue by SignalFlag** [infstellar/python-git-program-launcher#36]
![QQ截图20231006125226](https://github.com/infstellar/python-git-program-launcher/assets/37834746/1be413ff-9615-4b83-bbfa-4e0779af13da)
如图所示，无法安装win32 gui。

**Comment by SignalFlag** [comment]
[2023-10-06.log](https://github.com/infstellar/python-git-program-launcher/files/12826905/2023-10-06.log)

**Comment by SignalFlag** [comment]
[2023-10-06.log](https://github.com/infstellar/python-git-program-launcher/files/12827145/2023-10-06.log)

**Comment by frg666** [comment]
Same problem

**Comment by jackyliu16** [comment]
Some problems in Windows 10 (intel)

Could be solve by run `\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe -m pip install pypiwin32` **I GUESS**， which right now I was choking in installation of PyQt5-sip
Same operation when psutil, numpy, cv2, opencv-python, pillow, loguru, giadep, giaocr, giayolo, pywebio ...

You could see [requirement](https://gitee.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib/blob/main/requirements.txt) for more details information.

**Comment by jackyliu16** [comment]
Some problems in Windows 10 (intel)

Could be solve by run `\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe -m pip install pypiwin32` **I GUESS**， which right now I was choking in installation of PyQt5-sip
Same operation when psutil, numpy, cv2, opencv-python, pillow, loguru, giadep, giaocr, giayolo, pywebio ...

You could see [requirement](https://gitee.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib/blob/main/requirements.txt) for more details information.

**Comment by jackyliu16** [comment]
Some problems in Windows 10 (intel)

Could be solve by run `\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe -m pip install pypiwin32` **I GUESS**， which right now I was choking in installation of PyQt5-sip
Same operation when psutil, numpy, cv2, opencv-python, pillow, loguru, giadep, giaocr, giayolo, pywebio ...

You could see [requirement](https://gitee.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib/blob/main/requirements.txt) for more details information.

By the ways, `using the python.exe from \python\3.7.6_GIA_Launcher_Download_Lib\python.exe with pip install -r requirement.txt`

**Comment by jackyliu16** [comment]
Some problems in Windows 10 (intel)

Could be solve by run `\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe -m pip install pypiwin32` **I GUESS**， which right now I was choking in installation of PyQt5-sip
Same operation when psutil, numpy, cv2, opencv-python, pillow, loguru, giadep, giaocr, giayolo, pywebio ...

You could see [requirement](https://gitee.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib/blob/main/requirements.txt) for more details information.

By the ways, `using the python.exe from \python\3.7.6_GIA_Launcher_Download_Lib\python.exe with pip install -r requirement.txt`

**Comment by jackyliu16** [comment]
I have tried the portable method, but I couldn't solve the problem of PyQt5-sip.
It seems the reason is related to the INCLUDE folder not existing in the current version.

1. I have fully clone [genshin_impact_assistant](https://github.com/infstellar/genshin_impact_assistant) repo, and `git submodule init; git submodule update;`
2. I have installation and setting as PATH of the same version as this portable method provided, which is 3.7.6.
3. Just run `installer_setup.py` and `genshin_assistant.py` it will open a web.

![image](https://github.com/infstellar/python-git-program-launcher/assets/50787361/7bd471d9-0e8a-4b2c-97ba-96609dad22ad)

我尝试过移植的方法，但我不能解决PyQt 5-sip的问题。 原因似乎与当前版本中不存在的INCLUDE文件夹有关。
 1.我已经完全克隆了[genshin_impact_assistant]（https：//github.com/infstellar/genshin_impact_assistant）repo，以及`git子模块init; git submodule update;`
 2.我有安装和设置为相同版本的路径作为这个便携式方法提供，这是3.7.6。
 3.只要运行`installer_setup.py`和`genshin_assistant.py`，它将打开一个网站。

**Comment by frg666** [comment]
> I have tried the portable method, but I couldn't solve the problem of PyQt5-sip. It seems the reason is related to the INCLUDE folder not existing in the current version.
> 
>     1. I have fully clone [genshin_impact_assistant](https://github.com/infstellar/genshin_impact_assistant) repo, and `git submodule init; git submodule update;`
> 
>     2. I have installation and setting as PATH of the same version as this portable method provided, which is 3.7.6.
> 
>     3. Just run `installer_setup.py` and `genshin_assistant.py` it will open a web.
> 
> 
> ![image](https://user-images.githubusercontent.com/50787361/275595597-7bd471d9-0e8a-4b2c-97ba-96609dad22ad.png)
> 
> 我尝试过使用这个帮助工具，但我不能解决PyQt 5-sip的问题。 原因似乎与当前版本中不存在的INCLUDE文件夹有关。 1.我完全克隆了[genshin_impact_assistant](https://github.com/infstellar/genshin_impact_assistant) repo，以及`git submodule init; git submodule update;` 2.我安装了3.7.6的python，并且设置他作为了环境变量。 3.只要运行`installer_setup.py`和`genshin_assistant.py`，它将打开一个网站。

yes ，i cant install PyQt5-sip too

**Comment by jackyliu16** [comment]
@frg666 maybe you could try the ways that I provide.

**Comment by jllobvemy** [comment]
将source/util.py 中的
![image](https://github.com/infstellar/python-git-program-launcher/assets/61646964/51215991-0a8b-4247-b6cf-c736c4af95c0)
改为
![image](https://github.com/infstellar/python-git-program-launcher/assets/61646964/84fdae98-5ed3-47d0-ac76-d368d2a5f65f)
可以解决

**Comment by infstellar** [comment]
可能由于pyqt5无法编译引起,已修复

**Comment by infstellar** [comment]
fixed in 1.0.0.1159

**Comment by sanyueqi520** [comment]
我win10也碰到这个问题了，下载的是最新版本

**Comment by sanyueqi520** [comment]
> 我win10也碰到这个问题了，下载的是最新版本

并未解决

**Comment by infstellar** [comment]
> 我win10也碰到这个问题了，下载的是最新版本

试试 https://github.com/infstellar/python-git-program-launcher/releases/tag/v2.4.0.beta-1
如果还不能解决，发一下日志源文件

**Comment by warning-Kirov-reporting** [comment]
[2024-05-27.log](https://github.com/infstellar/python-git-program-launcher/files/15455538/2024-05-27.log)
![屏幕截图 2024-05-27 200258](https://github.com/infstellar/python-git-program-launcher/assets/125451655/a53665e7-b444-48dc-a25d-bc87f37730e6)
使用正式版最新版仍然有一样的报错，但是使用2.4.0 beta1出现这个报错

**Comment by warning-Kirov-reporting** [comment]
> [2024-05-27.log](https://github.com/infstellar/python-git-program-launcher/files/15455538/2024-05-27.log) ![屏幕截图 2024-05-27 200258](https://private-user-images.githubusercontent.com/125451655/334094114-a53665e7-b444-48dc-a25d-bc87f37730e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjIxNzksIm5iZiI6MTcxNjgyMTg3OSwicGF0aCI6Ii8xMjU0NTE2NTUvMzM0MDk0MTE0LWE1MzY2NWU3LWI0NDQtNDhkYy1hMjVkLWJjODdmMzc3MzBlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNDU3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YThlM2YwMzVlYWZiYzlkZGQxN2NjNzI2OThkZTIwZDM4NDJkNDAxMjI1MDQ3N2E3NmExZDI2MWIwMDU1Y2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aHl0AuQLg7Vzf7ShMCOvJqMGaqG_JmzExtms0-opkT0) 使用正式版最新版仍然有一样的报错，但是使用2.4.0 beta1出现这个报错

换了台电脑，还是beta版本，网络问题解决了，但是仍然出现题主报错
[2024-05-27.log](https://github.com/infstellar/python-git-program-launcher/files/15457585/2024-05-27.log)

![屏幕截图 2024-05-27 231335](https://github.com/infstellar/python-git-program-launcher/assets/125451655/0b701fe3-1681-45f8-aaea-3ff558c4ee4f)

**Comment by infstellar** [comment]
> > [2024-05-27.log](https://github.com/infstellar/python-git-program-launcher/files/15455538/2024-05-27.log) ![屏幕截图 2024-05-27 200258](https://private-user-images.githubusercontent.com/125451655/334094114-a53665e7-b444-48dc-a25d-bc87f37730e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjIxNzksIm5iZiI6MTcxNjgyMTg3OSwicGF0aCI6Ii8xMjU0NTE2NTUvMzM0MDk0MTE0LWE1MzY2NWU3LWI0NDQtNDhkYy1hMjVkLWJjODdmMzc3MzBlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNDU3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YThlM2YwMzVlYWZiYzlkZGQxN2NjNzI2OThkZTIwZDM4NDJkNDAxMjI1MDQ3N2E3NmExZDI2MWIwMDU1Y2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aHl0AuQLg7Vzf7ShMCOvJqMGaqG_JmzExtms0-opkT0) 使用正式版最新版仍然有一样的报错，但是使用2.4.0 beta1出现这个报错
> 
> 换了台电脑，还是beta版本，网络问题解决了，但是仍然出现题主报错 [2024-05-27.log](https://github.com/infstellar/python-git-program-launcher/files/15457585/2024-05-27.log)
> 
> ![屏幕截图 2024-05-27 231335](https://private-user-images.githubusercontent.com/125451655/334149271-0b701fe3-1681-45f8-aaea-3ff558c4ee4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTQyMTcsIm5iZiI6MTcyMDA5MzkxNywicGF0aCI6Ii8xMjU0NTE2NTUvMzM0MTQ5MjcxLTBiNzAxZmUzLTE2ODEtNDVmOC1hYWVhLTNmZjU1OGM0ZWU0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQxMTUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGI1MzI0YmZhMjk4Nzk0NDk5MDE3Nzg0YjNiZWEyNzM0YTNiOTcyMGQwMTRjNTBkYWIwODU2N2U5MTllN2Y2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c-nQ_EfbhXjigFf1as-k6Hxj-_xoIQMcs3Mk8OFFgFc)

修好了
