### ISSUE TITLE
启动Lanuncher.exe后报错

### ISSUE THREAD

**Issue by LiZhiEn030** [infstellar/python-git-program-launcher#39]
PATH=C:\Users\11216\Downloads\python-git-program-launcher-main\toolkit;C:\Users\11216\Downloads\python-git-program-launcher-main\toolkit\Scripts;C:\Users\11216\Downloads\python-git-program-launcher-main\toolkit\Lib;C:\Users\11216\Downloads\python-git-program-launcher-main\toolkit\Git\mingw64\bin;%PATH%
cd /d C:\Users\11216\Downloads\python-git-program-launcher-main && python -m gui
'python' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Fatal Error: Program Run Failure.
Running automatic error checking...
Possible reason: toolkit is not installed. Please check if you downloaded the correct file or if you cloned the submodule.
请按任意键继续. . .

**Comment by infstellar** [comment]
不要下载源代码,下载PGPL-2.3.7z
