### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 1413: invalid continuation byte

### ISSUE THREAD

**Issue by steven2076** [infstellar/python-git-program-launcher#40]
之前几个issues看了还是不懂如何解决，我路径既没中文又没空格的，用户名也是纯英文
2.2.1和2.1.0都一样
日志：
2023-11-08 15:46:08.974 | TRACE    | pgpl.utils:run_command:169 - Building wheels for collected packages: PyQt5-sip
2023-11-08 15:46:08.975 | TRACE    | pgpl.utils:run_command:169 - Building wheel for PyQt5-sip (pyproject.toml): started
2023-11-08 15:46:10.312 | TRACE    | pgpl.utils:run_command:169 - Building wheel for PyQt5-sip (pyproject.toml): finished with status 'error'
2023-11-08 15:46:10.317 | TRACE    | pgpl.utils:run_command:169 - Failed to build PyQt5-sip
2023-11-08 15:46:10.997 | ERROR    | pgpl.pages:_start:183 - 'utf-8' codec can't decode byte 0xce in position 1413: invalid continuation byte
Traceback (most recent call last):

  File "D:\PGPL-2.1.0\toolkit\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000021B047851F8>
    └ <Thread(Thread-4, started daemon 17944)>

  File "D:\PGPL-2.1.0\toolkit\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000021B04793F78>
    └ <Thread(Thread-4, started daemon 17944)>

  File "D:\PGPL-2.1.0\toolkit\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'callback': <function put_buttons.<locals>.click_callback at 0x0000021B07E3BF78>}
    │    │        │    │        └ <Thread(Thread-4, started daemon 17944)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4, started daemon 17944)>
    │    └ <function put_buttons.<locals>.click_callback at 0x0000021B07E3BE58>
    └ <Thread(Thread-4, started daemon 17944)>

  File "D:\PGPL-2.1.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
    │        └ {'event': 'callback', 'task_id': 'CB-click_callback-mSxeB5OfuZ', 'data': 0}
    └ <function put_buttons.<locals>.click_callback at 0x0000021B07E3BF78>

  File "D:\PGPL-2.1.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
           │       └ 0
           └ [<bound method MainPage._start of <pgpl.pages.MainPage object at 0x0000021B158A5708>>]

> File "D:\PGPL-2.1.0\pgpl\pages.py", line 155, in _start
    PipManager(launching_config, self.pt).pip_install(check_pip=check_pip, check_reqs=check_reqs)
    │          │                 │    │                         │                     └ True
    │          │                 │    │                         └ True
    │          │                 │    └ <pgpl.utils.ProgressTracker object at 0x0000021B158A5748>
    │          │                 └ <pgpl.pages.MainPage object at 0x0000021B158A5708>
    │          └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'ge...
    └ <class 'pgpl.managers.PipManager'>

  File "D:\PGPL-2.1.0\pgpl\managers.py", line 179, in pip_install
    self.execute(f'{self.pip()} install -r {self.requirements_file()}{self.pip_arg}')
    │    └ <function Command.execute at 0x0000021B080FC828>
    └ <pgpl.managers.PipManager object at 0x0000021B15483F08>

  File "D:\PGPL-2.1.0\pgpl\utils.py", line 244, in execute
    error_code, stdout, stderr = run_command(command, self.progress_tracker)
                                 │           │        │    └ <pgpl.utils.ProgressTracker object at 0x0000021B158A5748>
                                 │           │        └ <pgpl.managers.PipManager object at 0x0000021B15483F08>
                                 │           └ '"D:/PGPL-2.1.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install -r requirements.txt -i https://pypi...
                                 └ <function run_command at 0x0000021B080F1C18>

  File "D:\PGPL-2.1.0\pgpl\utils.py", line 186, in run_command
    return rc, stdout.decode('utf-8'), stderr.decode('utf-8')
           │   │      │                │      └ <method 'decode' of 'bytes' objects>
           │   │      │                └ b'  error: subprocess-exited-with-error\r\n  \r\n  Building wheel for PyQt5-sip (pyproject.toml) did not run successfully.\r\...
           │   │      └ <method 'decode' of 'bytes' objects>
           │   └ b''
           └ 1

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 1413: invalid continuation byte

**Comment by steven2076** [comment]
兄弟们，我成功了。
1、下载1.0.3版本  运行（开始下载依赖，环境不全然后就会报错）
2、安装vs_BuildTools       参考https://blog.csdn.net/no1xium/article/details/126764041
3、安装python3.7.6        复制include和libs到 \PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib
4、再次运行，应该就能把PyQt5-sip安装上了
5、最后如果要使用2.2.1版本，将1.0.3中的toolkit和repositories复制到2.2.1的目录下即可，不用覆盖

**Comment by infstellar** [comment]
fixed in 2.3
