### ISSUE TITLE
cant open main.py and python.exe

### ISSUE THREAD

**Issue by happyfachappyfac** [infstellar/python-git-program-launcher#41]
win 11
安装了python 3.7.6， 放到3.7.6_GIA_Launcher_Download_Lib也不行

[2023-11-08.log](https://github.com/infstellar/python-git-program-launcher/files/13295698/2023-11-08.log)
 
就是UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 20: invalid start byte 我自己不会修

**Comment by infstellar** [comment]
fixed in 2.3
