### ISSUE TITLE
依赖安装出错

### ISSUE THREAD

**Issue by helianzuiliu** [infstellar/python-git-program-launcher#45]
```
2023-11-30 13:42:36.823 | INFO     | pgpl.utils:run_command:219 - output: b'  Preparing metadata (setup.py): started\r\n'
2023-11-30 13:42:36.827 | TRACE    | pgpl.utils:run_command:228 - Preparing metadata (setup.py): started
2023-11-30 13:42:37.108 | INFO     | pgpl.utils:run_command:219 - output: b"  Preparing metadata (setup.py): finished with status 'error'\r\n"
2023-11-30 13:42:37.113 | TRACE    | pgpl.utils:run_command:228 - Preparing metadata (setup.py): finished with status 'error'
2023-11-30 13:42:37.301 | INFO     | pgpl.utils:run_command:219 - output: b''
2023-11-30 13:42:37.310 | INFO     | pgpl.utils:execute:330 - [ failure ], error_code: 1 stdout:  stderr:   error: subprocess-exited-with-error

  

  python setup.py egg_info did not run successfully.

  exit code: 1

  

  [6 lines of output]

  Traceback (most recent call last):

    File "<string>", line 36, in <module>

    File "<pip-setuptools-caller>", line 34, in <module>

    File "F:\Cache\pip-install-kpa4vyow\future_66654c5072f444dbab0e5da9d5b804e8\setup.py", line 86, in <module>

      import src.future

  ModuleNotFoundError: No module named 'src'

  [end of output]

  

  note: This error originates from a subprocess, and is likely not a problem with pip.

error: metadata-generation-failed



Encountered error while generating package metadata.



See above for output.



note: This is an issue with the package mentioned above, not pip.

hint: See above for details.


2023-11-30 13:42:37.314 | INFO     | pgpl.utils:show_error:266 - Update failed
2023-11-30 13:42:37.319 | INFO     | pgpl.utils:show_error:268 - 
2023-11-30 13:42:37.323 | INFO     | pgpl.utils:show_error:269 - Last command: "E:/NewFolder/PGPL-2.3/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install -r "E:/NewFolder/PGPL-2.3/toolkit/basic_requirements.txt" -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn
error_code: 1
2023-11-30 13:42:37.326 | INFO     | pgpl.utils:error_checking:261 - Running automatic error checking...
2023-11-30 13:42:37.332 | ERROR    | pgpl.pages:_start:227 - 
Traceback (most recent call last):

  File "E:\NewFolder\PGPL-2.3\pgpl\managers.py", line 193, in pip_install
    self.execute(f'{self.pip()} install -r {self.requirements_file()}{self.pip_arg}')
    │    └ <function Command.execute at 0x0000022189587318>
    └ <pgpl.managers.PipManager object at 0x00000221A8691A88>

  File "E:\NewFolder\PGPL-2.3\pgpl\utils.py", line 336, in execute
    raise ExecutionError
          └ <class 'pgpl.utils.ExecutionError'>

pgpl.utils.ExecutionError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "E:\NewFolder\PGPL-2.3\toolkit\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000022186E40CA8>
    └ <Thread(Thread-4, started daemon 26152)>
  File "E:\NewFolder\PGPL-2.3\toolkit\Lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000022186E40A68>
    └ <Thread(Thread-4, started daemon 26152)>
  File "E:\NewFolder\PGPL-2.3\toolkit\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'callback': <function put_buttons.<locals>.click_callback at 0x000002218A3968B8>}
    │    │        │    │        └ <Thread(Thread-4, started daemon 26152)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4, started daemon 26152)>
    │    └ <function put_buttons.<locals>.click_callback at 0x0000022189672948>
    └ <Thread(Thread-4, started daemon 26152)>
  File "E:\NewFolder\PGPL-2.3\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
    │        └ {'event': 'callback', 'task_id': 'CB-click_callback-Wf5u2IIYzv', 'data': 0}
    └ <function put_buttons.<locals>.click_callback at 0x000002218A3968B8>
  File "E:\NewFolder\PGPL-2.3\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
           │       └ 0
           └ [<bound method MainPage._start of <pgpl.pages.MainPage object at 0x000002218A457248>>]

> File "E:\NewFolder\PGPL-2.3\pgpl\pages.py", line 193, in _start
    PipManager(launching_config, self.pt).pip_install(check_pip=check_pip, check_reqs=check_reqs)
    │          │                 │    │                         │                     └ True
    │          │                 │    │                         └ False
    │          │                 │    └ <pgpl.utils.ProgressTracker object at 0x000002218A457288>
    │          │                 └ <pgpl.pages.MainPage object at 0x000002218A457248>
    │          └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': True, 'Main': 'gen...
    └ <class 'pgpl.managers.PipManager'>

  File "E:\NewFolder\PGPL-2.3\pgpl\managers.py", line 196, in pip_install
    self.update_pip()
    │    └ <function PipManager.update_pip at 0x000002218966BF78>
    └ <pgpl.managers.PipManager object at 0x00000221A8691A88>

  File "E:\NewFolder\PGPL-2.3\pgpl\managers.py", line 173, in update_pip
    self.execute(f'{self.pip()} install -r "{os.path.join(ROOT_PATH, "toolkit", "basic_requirements.txt")}"{self.pip_arg}')
    │    └ <function Command.execute at 0x0000022189587318>
    └ <pgpl.managers.PipManager object at 0x00000221A8691A88>

  File "E:\NewFolder\PGPL-2.3\pgpl\utils.py", line 336, in execute
    raise ExecutionError
          └ <class 'pgpl.utils.ExecutionError'>

pgpl.utils.ExecutionError

```

依赖安装有问题,禁用了更新pip更新检查

**Comment by helianzuiliu** [comment]
pip安装依赖的时候出现的奇怪bug，用手动输命令和直接使用本地安装包都会出错，但是可以在其他环境安装好的包复制进项目环境可以绕过这个bug

**Comment by infstellar** [comment]
准备把python安装方式改为用miniconda安装,之后应该不会再出现渣个问题了

**Comment by Liber1917** [comment]
<img width="1118" alt="image" src="https://github.com/infstellar/python-git-program-launcher/assets/108458660/0b8e33c3-0178-4cda-8124-b6ed33be0bda">
另一个依赖问题

**Comment by infstellar** [comment]
发一下日志文件，试试2.3版本 @Liber1917

**Comment by Liber1917** [comment]
[2023-12-01.log](https://github.com/infstellar/python-git-program-launcher/files/13527816/2023-12-01.log)
我先下个2.3试试

**Comment by Liber1917** [comment]
<img width="860" alt="image" src="https://github.com/infstellar/python-git-program-launcher/assets/108458660/112daefa-df56-4302-ae51-7edf01f1f1bb">
卡在安装torch

**Comment by Liber1917** [comment]
<img width="636" alt="image" src="https://github.com/infstellar/python-git-program-launcher/assets/108458660/ba99499b-446c-4880-901b-49d3aa973efe">
启动.exe文件执行情况

**Comment by infstellar** [comment]
@Liber1917 试试新的版本 https://github.com/infstellar/python-git-program-launcher/releases/tag/v2.4.0.beta-1

**Comment by Liber1917** [comment]
miniconda下载torch要花很长时间对吧

**Comment by Liber1917** [comment]
<img width="1225" alt="image" src="https://github.com/infstellar/python-git-program-launcher/assets/108458660/b46e5d4a-6e38-4937-b6ae-dc6ef0c2610e">
缺少另一个依赖

**Comment by Liber1917** [comment]
<img width="1225" alt="image" src="https://github.com/infstellar/python-git-program-launcher/assets/108458660/7924726e-69ac-43c8-b84d-922f3f441649">
还是缺少那个依赖

**Comment by infstellar** [comment]
发一下Launcher的log源文件看看
用glaglobal配置试试

**Comment by Liber1917** [comment]
[2023-12-03.log](https://github.com/infstellar/python-git-program-launcher/files/13537763/2023-12-03.log)
源文件

**Comment by infstellar** [comment]
> Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out'))': /simple/numpy/

开代理了吗

**Comment by Liber1917** [comment]
开了VPS，测

**Comment by infstellar** [comment]
删除installed_python之后重装试试
你在国外嘛

**Comment by Liber1917** [comment]
国内校园网，下载torch太慢所以搭了个ipv6的
俩月前的事了

**Comment by infstellar** [comment]
那还是用giachina配置吧
你的系统设置是外国吗,我看你的UI界面是英文

**Comment by Liber1917** [comment]
区域给的是美国(手动狗头)
现在整个人的电脑处于一个比较逆天的状态

**Comment by Liber1917** [comment]
<img width="1164" alt="image" src="https://github.com/infstellar/python-git-program-launcher/assets/108458660/47e75051-ee68-4248-9b39-7f579c9c80ea">
这个算是成功了嘛？
感觉不开代理很难下载torch，我最后是直接保留了开代理下载的依赖然后关代理重新跑一遍

**Comment by infstellar** [comment]
应该是
另外最好在GIA的设置里把语言改中文(

**Comment by Liber1917** [comment]
okok
我这边改不了，可能是多开了程序后又出现了报错
我再看看

**Comment by Liber1917** [comment]
<img width="729" alt="image" src="https://github.com/infstellar/python-git-program-launcher/assets/108458660/f05772d1-31d4-4c1e-8672-bab21556e848">

新的报错，在第二次使用launcher后出现了
刚刚直接python启动genshin_assistant.py也有问题，应该与这个python-git应用无关

**Comment by Liber1917** [comment]
直接配置GIA的lang设置后会弹出应用内部错误但是脚本能够运行

**Comment by infstellar** [comment]
把config/settings/General.json删除,然后重启程序试试
发一下GIA的日志源文件看看

**Comment by siltlotus** [comment]
你好，我这里也是在更新依赖的时候显示失败，请问怎么解决呢
![Uploading went.png…]()

**Comment by siltlotus** [comment]
> <img alt="image" width="1225" src="https://private-user-images.githubusercontent.com/108458660/287490691-7924726e-69ac-43c8-b84d-922f3f441649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzgwNzUsIm5iZiI6MTcxNjczNzc3NSwicGF0aCI6Ii8xMDg0NTg2NjAvMjg3NDkwNjkxLTc5MjQ3MjZlLTY5YWMtNDNjOC1iODRkLTkyMmYzZjQ0MTY0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxNTM2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGQ2YTkzZjZkODAxMzIyMzVjZjBiYjEzNzdmOWZhOGMwYjY5Y2IyZjRiNDc3YWFkMmFjNmZkN2Y1ODc0MGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zfm1vaS4svLCJHSxpGKLMVm97yJoqkQQyWep9jA7Ybo"> 还是缺少那个依赖

你好，请问你的这个问题是怎么解决的呢，我这里还是显示有这个问题

**Comment by infstellar** [comment]
> > <img alt="image" width="1225" src="https://private-user-images.githubusercontent.com/108458660/287490691-7924726e-69ac-43c8-b84d-922f3f441649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzgwNzUsIm5iZiI6MTcxNjczNzc3NSwicGF0aCI6Ii8xMDg0NTg2NjAvMjg3NDkwNjkxLTc5MjQ3MjZlLTY5YWMtNDNjOC1iODRkLTkyMmYzZjQ0MTY0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxNTM2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGQ2YTkzZjZkODAxMzIyMzVjZjBiYjEzNzdmOWZhOGMwYjY5Y2IyZjRiNDc3YWFkMmFjNmZkN2Y1ODc0MGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zfm1vaS4svLCJHSxpGKLMVm97yJoqkQQyWep9jA7Ybo"> 还是缺少那个依赖
> 
> 你好，请问你的这个问题是怎么解决的呢，我这里还是显示有这个问题

单开一个issue，这个太杂
