### ISSUE TITLE
截图失败，找不到原神

### ISSUE THREAD

**Issue by LeoxfZhou** [infstellar/python-git-program-launcher#47]
![Screenshot 2023-12-02 223708](https://github.com/infstellar/python-git-program-launcher/assets/105604401/6bda7050-68e4-473f-85f6-7e4fda99f924)
设置什么的都调好了（分辨率，if全屏之类的）。美服，global和china都试过了。原神打开的时候，PGPL在后台运行，但是原神没有反应，PGPL一直显示截图失败。求解

**Comment by infstellar** [comment]
右下角的原神启动器关了吗

**Comment by LeoxfZhou** [comment]
原神的launcher在打开原神的时候就消失了，不知道是不是关闭，底下没显示图标的应该是这个cmd.exe

**Comment by LeoxfZhou** [comment]
> 右下角的原神启动器关了吗

原神的launcher在打开原神的时候就消失了，不知道是不是关闭，底下没显示图标的应该是这个cmd.exe

**Comment by infstellar** [comment]
右下角，点一下向上小箭头，看里面有没有原神启动器

**Comment by infstellar** [comment]
点一下右下角的向上小箭头看看有没有原神启动器

**Comment by LeoxfZhou** [comment]
> 点一下右下角的向上小箭头看看有没有原神启动器

是的！就是这个问题，现在可以用了，感谢
